
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
  namespace: product
data:
  DB_HOST: "product-postgres"
  DB_PORT: "5432"
  DB_NAME: "products_db"
  SERVER_PORT: "8081"
  TIME_ZONE: "Africa/Tunis"
