
apiVersion: v1
kind: Service
metadata:
  name: product-web
  namespace: product
spec:
  selector:
    app: product-web
  ports:
    - name: http
      port: 80
      targetPort: 8081
      nodePort: 30080
  type: NodePort
