
apiVersion: v1
kind: Service
metadata:
  name: product-postgres
  namespace: product
spec:
  selector:
    app: product-postgres
  ports:
    - name: pg
      port: 5432
      targetPort: 5432
  type: ClusterIP
